name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 16

      - name: Build
        run: yarn install && yarn build

      - name: Run tests
        run: yarn test

      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage/coverage-final.json
          fail_ci_if_error: true
